import { localized } from './i18n'
import type { AppState, PlanTier } from './types'

export const planTiers: PlanTier[] = [
  {
    id: 'community',
    name: localized('Community', 'Community'),
    strapline: localized(
      'Great for smaller nonprofits that need structure fast.',
      'Ideal pour les petits OBNL qui veulent de la structure rapidement.',
    ),
    priceCad: 0,
    volunteerCap: 25,
    adminCap: 1,
    smartMatchCap: 0,
    features: [
      localized('Pipeline hub', 'Hub des candidatures'),
      localized('Volunteer profiles', 'Profils benevoles'),
      localized('Dashboard + activity tracking', 'Tableau de bord + suivi'),
      localized('Volunteer timesheets', 'Feuilles de temps benevoles'),
      localized('Core onboarding timeline', 'Chronologie d integration de base'),
    ],
  },
  {
    id: 'momentum',
    name: localized('Momentum', 'Momentum'),
    strapline: localized(
      'For coordinators who need smarter recruitment and follow-up.',
      'Pour les coordonnateurs qui veulent un recrutement et un suivi plus intelligents.',
    ),
    priceCad: 20,
    volunteerCap: 100,
    adminCap: 3,
    smartMatchCap: 100,
    features: [
      localized('Everything in Community', 'Tout ce qui est dans Community'),
      localized('Training videos + quizzes', 'Videos de formation + quiz'),
      localized('Interview hub', 'Hub des entrevues'),
      localized('Matching + communication', 'Jumelage + communication'),
      localized('Automated reminders', 'Rappels automatises'),
    ],
  },
  {
    id: 'network',
    name: localized('Network', 'Network'),
    strapline: localized(
      'For multi-site operations that need oversight, safety, and scale.',
      'Pour les operations multisites qui ont besoin de supervision, de securite et d echelle.',
    ),
    priceCad: 50,
    volunteerCap: 'unlimited',
    adminCap: 'unlimited',
    smartMatchCap: 'unlimited',
    features: [
      localized('Everything in Momentum', 'Tout ce qui est dans Momentum'),
      localized('Multi-site oversight', 'Supervision multisite'),
      localized('Incident reporting', 'Signalement d incidents'),
      localized('Advanced reporting', 'Rapports avances'),
      localized('Unlimited smart matches', 'Jumelages intelligents illimites'),
    ],
  },
]

export const seedAppState: AppState = {
  currentPlanId: 'momentum',
  smartMatchUsage: 42,
  volunteers: [
    {
      id: 'v-amelie',
      firstName: 'Amelie',
      lastName: 'Gagnon',
      status: 'active',
      organization: 'McGill Student Wellness Hub',
      location: 'Downtown Campus',
      availability: ['weekdays', 'evenings'],
      interests: ['mentoring', 'events', 'outreach'],
      experience: localized(
        'Led peer mentoring and event support across two student orientation seasons.',
        'A mene du mentorat par les pairs et du soutien evenementiel pendant deux saisons d orientation.',
      ),
      physicalRequirements: ['indoor', 'bilingual'],
      tshirtSize: 'M',
      dietaryRestrictions: 'Vegetarian',
      languages: ['English', 'French'],
      joinedAt: '2026-01-18',
      notes: localized(
        'Strong with anxious first-time applicants. Comfortable moderating group orientation.',
        'Tres a l aise avec les nouveaux candidats anxieux. Peut animer une orientation de groupe.',
      ),
      supervisor: {
        name: 'Nadia Hassan',
        role: 'Volunteer Coordinator',
        phone: '514-555-0124',
        email: 'nadia.hassan@voluntreal.demo',
      },
      facilitySupervisor: {
        name: 'Camille Tremblay',
        role: 'Facility Supervisor',
        phone: '514-555-0183',
        email: 'camille.tremblay@voluntreal.demo',
      },
      managerOnCall: {
        name: 'Olivier Garon',
        role: 'Manager on Call',
        phone: '514-555-0199',
        email: 'oncall@voluntreal.demo',
      },
    },
    {
      id: 'v-jay',
      firstName: 'Jay',
      lastName: 'Bennett',
      status: 'applicant',
      organization: 'CIUSSS Centre-Sud',
      location: 'CHSLD Saint-Henri',
      availability: ['weekends', 'flexible'],
      interests: ['patient-support', 'outreach'],
      experience: localized(
        'Completed patient ambassador training and worked at two community clinics.',
        'A complete une formation d ambassadeur patient et a travaille dans deux cliniques communautaires.',
      ),
      physicalRequirements: ['standing', 'bilingual', 'indoor'],
      tshirtSize: 'L',
      dietaryRestrictions: 'Nut allergy',
      languages: ['English', 'French'],
      joinedAt: '2026-02-08',
      notes: localized(
        'Waiting on one final reference before activation.',
        'En attente d une derniere reference avant l activation.',
      ),
      supervisor: {
        name: 'Sarah Wong',
        role: 'Site Coordinator',
        phone: '514-555-0147',
        email: 'sarah.wong@voluntreal.demo',
      },
      facilitySupervisor: {
        name: 'Luc Beaulieu',
        role: 'Facility Supervisor',
        phone: '514-555-0112',
        email: 'luc.beaulieu@voluntreal.demo',
      },
      managerOnCall: {
        name: 'Olivier Garon',
        role: 'Manager on Call',
        phone: '514-555-0199',
        email: 'oncall@voluntreal.demo',
      },
    },
    {
      id: 'v-salma',
      firstName: 'Salma',
      lastName: 'El Idrissi',
      status: 'active',
      organization: 'Moisson Montreal',
      location: 'Saint-Laurent',
      availability: ['weekdays', 'weekends'],
      interests: ['food-security', 'admin'],
      experience: localized(
        'Warehouse sorting lead with strong inventory discipline and volunteer coaching experience.',
        'Chef d equipe au tri en entrepot avec une forte discipline d inventaire et de mentorat.',
      ),
      physicalRequirements: ['lifting', 'standing', 'indoor'],
      tshirtSize: 'S',
      dietaryRestrictions: 'Halal meals preferred',
      languages: ['French', 'Arabic', 'English'],
      joinedAt: '2025-11-12',
      notes: localized(
        'Often helps train new volunteers during high-volume food drives.',
        'Aide souvent a former les nouveaux benevoles pendant les collectes alimentaires.',
      ),
      supervisor: {
        name: 'Marc Dube',
        role: 'Operations Lead',
        phone: '514-555-0175',
        email: 'marc.dube@voluntreal.demo',
      },
      facilitySupervisor: {
        name: 'Sonia Patel',
        role: 'Warehouse Supervisor',
        phone: '514-555-0131',
        email: 'sonia.patel@voluntreal.demo',
      },
      managerOnCall: {
        name: 'Olivier Garon',
        role: 'Manager on Call',
        phone: '514-555-0199',
        email: 'oncall@voluntreal.demo',
      },
    },
    {
      id: 'v-noah',
      firstName: 'Noah',
      lastName: 'Lefebvre',
      status: 'active',
      organization: 'Bienvenue NDG',
      location: 'NDG',
      availability: ['evenings', 'weekends'],
      interests: ['events', 'mentoring', 'admin'],
      experience: localized(
        'Ran newcomer welcome desks and volunteer scheduling for neighbourhood events.',
        'A gere des comptoirs d accueil pour nouveaux arrivants et l horaire benevole lors d evenements.',
      ),
      physicalRequirements: ['indoor', 'outdoor', 'bilingual'],
      tshirtSize: 'XL',
      dietaryRestrictions: 'None',
      languages: ['French', 'English'],
      joinedAt: '2025-09-09',
      notes: localized(
        'Reliable with weekend coverage and volunteer phone support.',
        'Tres fiable pour la couverture des fins de semaine et le soutien telephonique.',
      ),
      supervisor: {
        name: 'Evelyn Roy',
        role: 'Community Programs Manager',
        phone: '514-555-0166',
        email: 'evelyn.roy@voluntreal.demo',
      },
      facilitySupervisor: {
        name: 'David Sinclair',
        role: 'Facility Supervisor',
        phone: '514-555-0109',
        email: 'david.sinclair@voluntreal.demo',
      },
      managerOnCall: {
        name: 'Olivier Garon',
        role: 'Manager on Call',
        phone: '514-555-0199',
        email: 'oncall@voluntreal.demo',
      },
    },
    {
      id: 'v-maya',
      firstName: 'Maya',
      lastName: 'Sullivan',
      status: 'applicant',
      organization: 'Women on the Rise',
      location: 'Montreal North',
      availability: ['weekdays'],
      interests: ['outreach', 'admin', 'food-security'],
      experience: localized(
        'Helped intake teams at a local shelter and enjoys structured admin work.',
        'A aide des equipes d accueil dans un refuge local et aime le travail administratif structure.',
      ),
      physicalRequirements: ['indoor'],
      tshirtSize: 'M',
      dietaryRestrictions: 'Gluten free',
      languages: ['English'],
      joinedAt: '2026-03-02',
      notes: localized(
        'Best suited to intake, meal support, or coordinator assistance.',
        'Convient bien a l accueil, au soutien repas ou a l assistance de coordination.',
      ),
      supervisor: {
        name: 'Anais Joseph',
        role: 'Volunteer Coordinator',
        phone: '514-555-0180',
        email: 'anais.joseph@voluntreal.demo',
      },
      facilitySupervisor: {
        name: 'Marissa Hall',
        role: 'Facility Supervisor',
        phone: '514-555-0129',
        email: 'marissa.hall@voluntreal.demo',
      },
      managerOnCall: {
        name: 'Olivier Garon',
        role: 'Manager on Call',
        phone: '514-555-0199',
        email: 'oncall@voluntreal.demo',
      },
    },
  ],
  roles: [
    {
      id: 'role-campus',
      title: localized('Campus welcome guide', 'Guide d accueil campus'),
      organization: 'McGill Student Wellness Hub',
      location: 'Downtown Campus',
      premium: true,
      openings: 3,
      shiftPattern: localized('Tuesday and Thursday evenings', 'Mardi et jeudi soirs'),
      description: localized(
        'Welcome students, support check-in, and help direct them toward services during busy orientation weeks.',
        'Accueillir les etudiants, aider au pointage et les diriger vers les services pendant les semaines d orientation.',
      ),
      interestTags: ['events', 'mentoring', 'outreach'],
      requirementTags: ['bilingual', 'indoor'],
    },
    {
      id: 'role-clinic',
      title: localized('Clinic hospitality volunteer', 'Benevole d accueil clinique'),
      organization: 'CIUSSS Centre-Sud',
      location: 'CHSLD Saint-Henri',
      premium: true,
      openings: 2,
      shiftPattern: localized('Saturday mornings', 'Samedi matin'),
      description: localized(
        'Support visitors, escort patients, and monitor waiting areas with calm, bilingual communication.',
        'Soutenir les visiteurs, accompagner les patients et surveiller les salles d attente avec une communication bilingue calme.',
      ),
      interestTags: ['patient-support', 'outreach'],
      requirementTags: ['standing', 'bilingual', 'indoor'],
    },
    {
      id: 'role-foodbank',
      title: localized('Warehouse sorting lead', 'Responsable du tri en entrepot'),
      organization: 'Moisson Montreal',
      location: 'Saint-Laurent',
      premium: false,
      openings: 4,
      shiftPattern: localized('Weekday mornings', 'Jours de semaine le matin'),
      description: localized(
        'Sort and prep food hampers while guiding first-time volunteers on safe, efficient workflows.',
        'Trier et preparer les paniers alimentaires tout en guidant les nouveaux benevoles sur des flux securitaires.',
      ),
      interestTags: ['food-security', 'admin'],
      requirementTags: ['lifting', 'standing', 'indoor'],
    },
    {
      id: 'role-outreach',
      title: localized('Community outreach host', 'Animateur de rayonnement'),
      organization: 'Bienvenue NDG',
      location: 'NDG',
      premium: false,
      openings: 2,
      shiftPattern: localized('Weekend events', 'Evenements de fin de semaine'),
      description: localized(
        'Run welcome desks, distribute multilingual materials, and help families navigate local services.',
        'Animer les comptoirs d accueil, distribuer du materiel multilingue et aider les familles a trouver les services locaux.',
      ),
      interestTags: ['events', 'outreach', 'mentoring'],
      requirementTags: ['outdoor', 'bilingual'],
    },
  ],
  applications: [
    {
      id: 'app-001',
      volunteerId: 'v-jay',
      roleId: 'role-clinic',
      source: 'cabm',
      stage: 'interview',
      note: localized(
        'Candidate has healthcare empathy and strong bilingual comfort.',
        'Le candidat montre de l empathie en milieu de sante et une forte aisance bilingue.',
      ),
      submittedAt: '2026-02-08',
      lastUpdated: '2026-03-29',
      timeline: [
        {
          id: 't-001',
          type: 'application',
          date: '2026-02-08',
          title: localized('Application received', 'Candidature recue'),
          detail: localized(
            'Imported from Centre d action benevole into the centralized pipeline.',
            'Importee du Centre d action benevole dans le pipeline centralise.',
          ),
        },
        {
          id: 't-002',
          type: 'reference',
          date: '2026-02-14',
          title: localized('Reference requested', 'Reference demandee'),
          detail: localized(
            'One reference submitted; one still pending with a one-week follow-up reminder.',
            'Une reference recue; une autre encore en attente avec rappel apres une semaine.',
          ),
        },
        {
          id: 't-003',
          type: 'interview',
          date: '2026-03-29',
          title: localized('Interview suggested', 'Entrevue suggeree'),
          detail: localized(
            'A bilingual Saturday slot has been proposed based on coordinator availability.',
            'Une plage bilingue du samedi a ete proposee selon les disponibilites du coordonnateur.',
          ),
        },
      ],
    },
    {
      id: 'app-002',
      volunteerId: 'v-maya',
      roleId: 'role-foodbank',
      source: 'website',
      stage: 'review',
      note: localized(
        'Strong admin fit and availability during weekday prep shifts.',
        'Bon profil administratif et disponibilite pendant les quarts de preparation en semaine.',
      ),
      submittedAt: '2026-03-02',
      lastUpdated: '2026-03-30',
      timeline: [
        {
          id: 't-004',
          type: 'application',
          date: '2026-03-02',
          title: localized('Application received', 'Candidature recue'),
          detail: localized(
            'Submitted through the website pipeline and standardized automatically.',
            'Soumise par le site web et standardisee automatiquement.',
          ),
        },
        {
          id: 't-005',
          type: 'reference',
          date: '2026-03-06',
          title: localized('Reference deadline set', 'Echeance de reference fixee'),
          detail: localized(
            'Volunteer was given seven days to upload one community reference.',
            'La benevole a recu sept jours pour televerser une reference communautaire.',
          ),
        },
      ],
    },
    {
      id: 'app-003',
      volunteerId: 'v-amelie',
      roleId: 'role-campus',
      source: 'mcgill',
      stage: 'active',
      note: localized(
        'Activated quickly after a strong orientation and interview.',
        'Activation rapide apres une excellente orientation et entrevue.',
      ),
      submittedAt: '2026-01-18',
      lastUpdated: '2026-02-01',
      timeline: [
        {
          id: 't-006',
          type: 'application',
          date: '2026-01-18',
          title: localized('Application received', 'Candidature recue'),
          detail: localized(
            'Imported from a McGill community engagement fair.',
            'Importee a partir d une foire d engagement communautaire de McGill.',
          ),
        },
        {
          id: 't-007',
          type: 'interview',
          date: '2026-01-21',
          title: localized('Interview booked', 'Entrevue reservee'),
          detail: localized(
            'Booked directly from the interview hub after email outreach.',
            'Reservee directement depuis le hub des entrevues apres l envoi du courriel.',
          ),
        },
        {
          id: 't-008',
          type: 'training',
          date: '2026-01-25',
          title: localized('Orientation completed', 'Orientation completee'),
          detail: localized(
            'Volunteer passed the orientation video and quiz on the first try.',
            'La benevole a reussi la video d orientation et le quiz du premier coup.',
          ),
        },
      ],
    },
  ],
  matches: [
    {
      id: 'match-001',
      roleId: 'role-campus',
      volunteerId: 'v-amelie',
      score: 96,
      revealed: true,
      status: 'booked',
      rationale: localized(
        'Excellent bilingual event fit with mentoring experience and prior orientation work.',
        'Excellente correspondance bilingue pour un role evenementiel avec experience en mentorat et orientation.',
      ),
      emailTemplateId: 'email-campus',
    },
    {
      id: 'match-002',
      roleId: 'role-clinic',
      volunteerId: 'v-jay',
      score: 94,
      revealed: true,
      status: 'responded',
      rationale: localized(
        'High empathy score, healthcare comfort, and bilingual availability for weekend shifts.',
        'Score d empathie eleve, aisance en sante et disponibilite bilingue pour les quarts de fin de semaine.',
      ),
      emailTemplateId: 'email-interview',
    },
    {
      id: 'match-003',
      roleId: 'role-foodbank',
      volunteerId: 'v-salma',
      score: 91,
      revealed: true,
      status: 'emailed',
      rationale: localized(
        'Already trusted during warehouse onboarding and can coach newer volunteers safely.',
        'Deja digne de confiance a l entrepot et capable d accompagner les nouveaux benevoles en securite.',
      ),
      emailTemplateId: 'email-role',
    },
    {
      id: 'match-004',
      roleId: 'role-outreach',
      volunteerId: 'v-noah',
      score: 89,
      revealed: false,
      status: 'suggested',
      rationale: localized(
        'Strong multilingual event support and weekend attendance consistency.',
        'Fort soutien evenementiel multilingue et grande constance les fins de semaine.',
      ),
      emailTemplateId: 'email-role',
    },
    {
      id: 'match-005',
      roleId: 'role-foodbank',
      volunteerId: 'v-maya',
      score: 86,
      revealed: false,
      status: 'suggested',
      rationale: localized(
        'Good weekday availability and admin interest for warehouse prep workflows.',
        'Bonne disponibilite en semaine et interet administratif pour la preparation en entrepot.',
      ),
      emailTemplateId: 'email-role',
    },
  ],
  emailTemplates: [
    {
      id: 'email-role',
      name: 'Role shortlist',
      subject: localized('A volunteer role that fits your profile', 'Un role benevole qui correspond a votre profil'),
      body: localized(
        'Hi there, based on your availability and experience, we would love to invite you to review this volunteer role.',
        'Bonjour, selon vos disponibilites et votre experience, nous aimerions vous inviter a examiner ce role benevole.',
      ),
    },
    {
      id: 'email-interview',
      name: 'Interview invitation',
      subject: localized('Select an interview time that works for you', 'Choisissez une plage d entrevue qui vous convient'),
      body: localized(
        'Thanks for your application. You can select one of the suggested interview slots directly from this message.',
        'Merci pour votre candidature. Vous pouvez choisir une des plages d entrevue suggerees directement a partir de ce message.',
      ),
    },
    {
      id: 'email-campus',
      name: 'Campus onboarding',
      subject: localized('Welcome to the volunteer onboarding path', 'Bienvenue dans le parcours d integration benevole'),
      body: localized(
        'You have been selected for the next stage. Please complete the short training module before orientation.',
        'Vous avez ete selectionne pour la prochaine etape. Veuillez completer le court module de formation avant l orientation.',
      ),
    },
  ],
  trainings: [
    {
      id: 'training-001',
      title: localized('Orientation essentials', 'Essentiels de l orientation'),
      summary: localized(
        'Mission, tone, confidentiality, and what volunteers should never improvise on-site.',
        'Mission, ton, confidentialite et ce que les benevoles ne doivent jamais improviser sur le terrain.',
      ),
      lengthMinutes: 9,
      question: localized(
        'What should a volunteer do if a participant asks for medical guidance?',
        'Que doit faire un benevole si un participant demande un conseil medical?',
      ),
      options: [
        localized('Answer from personal experience', 'Repondre selon son experience personnelle'),
        localized('Escalate to staff or the on-call manager', 'Escalader vers le personnel ou le gestionnaire de garde'),
        localized('Search online and come back later', 'Faire une recherche en ligne puis revenir'),
      ],
      correctAnswer: 1,
      assignedVolunteerIds: ['v-amelie', 'v-jay', 'v-maya'],
      completionByVolunteer: {
        'v-amelie': { selectedAnswer: 1, completedAt: '2026-01-25' },
        'v-jay': { selectedAnswer: null, completedAt: null },
        'v-maya': { selectedAnswer: null, completedAt: null },
      },
    },
    {
      id: 'training-002',
      title: localized('Safety and incident basics', 'Securite et notions d incident'),
      summary: localized(
        'How to report injuries, near misses, and unsafe conditions without delay.',
        'Comment signaler rapidement les blessures, incidents evitables et conditions dangereuses.',
      ),
      lengthMinutes: 7,
      question: localized(
        'When should a near miss be documented?',
        'Quand faut-il documenter un quasi-incident?',
      ),
      options: [
        localized('Only if someone complains later', 'Seulement si quelqu un se plaint plus tard'),
        localized('At the end of the month', 'A la fin du mois'),
        localized('As soon as the shift safely allows it', 'Des que le quart le permet en toute securite'),
      ],
      correctAnswer: 2,
      assignedVolunteerIds: ['v-jay', 'v-salma'],
      completionByVolunteer: {
        'v-jay': { selectedAnswer: null, completedAt: null },
        'v-salma': { selectedAnswer: 2, completedAt: '2026-02-16' },
      },
    },
  ],
  interviews: [
    {
      id: 'slot-001',
      roleId: 'role-clinic',
      start: '2026-04-04T09:00:00',
      end: '2026-04-04T09:30:00',
      interviewer: 'Sarah Wong',
      meetingMode: 'virtual',
      location: localized('Zoom interview room A', 'Salle Zoom A'),
      bookedVolunteerId: 'v-jay',
    },
    {
      id: 'slot-002',
      roleId: 'role-clinic',
      start: '2026-04-04T10:00:00',
      end: '2026-04-04T10:30:00',
      interviewer: 'Sarah Wong',
      meetingMode: 'virtual',
      location: localized('Zoom interview room A', 'Salle Zoom A'),
      bookedVolunteerId: null,
    },
    {
      id: 'slot-003',
      roleId: 'role-campus',
      start: '2026-04-05T17:00:00',
      end: '2026-04-05T17:30:00',
      interviewer: 'Nadia Hassan',
      meetingMode: 'onsite',
      location: localized('Brown Student Services, room 210', 'Services aux etudiants Brown, salle 210'),
      bookedVolunteerId: null,
    },
    {
      id: 'slot-004',
      roleId: 'role-foodbank',
      start: '2026-04-06T08:30:00',
      end: '2026-04-06T09:00:00',
      interviewer: 'Marc Dube',
      meetingMode: 'onsite',
      location: localized('Warehouse office', 'Bureau de l entrepot'),
      bookedVolunteerId: null,
    },
  ],
  alerts: [
    {
      id: 'alert-001',
      volunteerId: 'v-jay',
      deadline: '2026-04-03',
      status: 'open',
      title: localized('Reference due in 24 hours', 'Reference due dans 24 heures'),
      detail: localized(
        'Jay still needs to upload one final reference before activation.',
        'Jay doit encore televerser une derniere reference avant l activation.',
      ),
    },
    {
      id: 'alert-002',
      volunteerId: 'v-maya',
      deadline: '2026-04-07',
      status: 'sent',
      title: localized('Orientation confirmation pending', 'Confirmation d orientation en attente'),
      detail: localized(
        'A reminder email was sent to confirm attendance for food bank orientation.',
        'Un rappel a ete envoye pour confirmer la presence a l orientation de la banque alimentaire.',
      ),
    },
    {
      id: 'alert-003',
      volunteerId: 'v-amelie',
      deadline: '2026-04-10',
      status: 'resolved',
      title: localized('Supervisor check-in complete', 'Suivi de supervision complete'),
      detail: localized(
        'Post-onboarding check-in was logged and the volunteer is now marked active.',
        'Le suivi post-integration a ete consigne et la benevole est maintenant active.',
      ),
    },
  ],
  timesheets: [
    {
      id: 'ts-001',
      volunteerId: 'v-amelie',
      date: '2026-03-18',
      hours: 4,
      rating: 5,
      feedback: localized(
        'Loved having the timeline and direct supervisor contact in one place.',
        'J ai aime avoir la chronologie et le contact du superviseur au meme endroit.',
      ),
    },
    {
      id: 'ts-002',
      volunteerId: 'v-amelie',
      date: '2026-03-25',
      hours: 3.5,
      rating: 4,
      feedback: localized(
        'Orientation content was clear and the shift handoff felt smooth.',
        'Le contenu d orientation etait clair et la transition de quart etait fluide.',
      ),
    },
    {
      id: 'ts-003',
      volunteerId: 'v-salma',
      date: '2026-03-20',
      hours: 5,
      rating: 5,
      feedback: localized(
        'The training quiz helped new volunteers ask fewer repetitive questions.',
        'Le quiz de formation a aide les nouveaux benevoles a poser moins de questions repetitives.',
      ),
    },
    {
      id: 'ts-004',
      volunteerId: 'v-noah',
      date: '2026-03-21',
      hours: 2.5,
      rating: 4,
      feedback: localized(
        'Would love one click access to outreach event briefing notes.',
        'J aimerais avoir un acces en un clic aux notes de briefing pour les evenements.',
      ),
    },
  ],
  incidents: [
    {
      id: 'incident-001',
      volunteerId: 'v-salma',
      date: '2026-02-12',
      severity: 'low',
      description: localized(
        'A stack of bins became unstable during unloading. No injury, but the area was cordoned and documented.',
        'Une pile de bacs est devenue instable pendant le dechargement. Aucune blessure, mais la zone a ete balisee et documentee.',
      ),
      resolved: true,
    },
  ],
}

export const cloneSeedState = (): AppState =>
  JSON.parse(JSON.stringify(seedAppState)) as AppState
